version: '3.8'

services:
  apk-converter:
    build: .
    container_name: apk-debug-converter
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    volumes:
      - ./temp:/app/temp
      - ./uploads:/app/uploads
      - ./output:/app/output
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - apk-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: apk-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - apk-converter
    networks:
      - apk-network

networks:
  apk-network:
    driver: bridge

volumes:
  temp_data:
  uploads_data:
  output_data: